ALTER TABLE `best`
ADD COLUMN `address` VARCHAR(255) NULL DEFAULT NULL AFTER `longitude`,
ADD COLUMN `place` VARCHAR(255) NULL DEFAULT NULL AFTER `address`;

ALTER TABLE `utilisateur`
ADD COLUMN `address` VARCHAR(255) NULL DEFAULT NULL AFTER `longitude`,
ADD COLUMN `place` VARCHAR(255) NULL DEFAULT NULL AFTER `address`;
